/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author JunyoungBae
 */
public class FlightScheduler extends javax.swing.JFrame {
    private Passenger passenger = new Passenger();
    private Days date = new Days();
    private FlightManager flight = new FlightManager();
    private Booking booking = new Booking();
    private List<String> results;
    private List<List<String>> results2;
    private List<List<String>> result3;
    private Waitlist waitlist = new Waitlist();
    
    
    /**
     * Creates new form FlightScheduler
     */
    public FlightScheduler() {
        initComponents();
        PassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        DateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        WaitDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        FlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        CancelCustomerDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        CancelPassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        ConfirmCustomer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FlightNameText = new javax.swing.JTextField();
        SeatAmountText = new javax.swing.JTextField();
        AddFlight = new javax.swing.JButton();
        AddDay = new javax.swing.JButton();
        DateChooser = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PassengerCombo = new javax.swing.JComboBox<>();
        FlightCombo = new javax.swing.JComboBox<>();
        ConfirmBooking = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DateCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        StatusFlightCombo = new javax.swing.JComboBox<>();
        StatusDateCombo = new javax.swing.JComboBox<>();
        StatusConfirm = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        WaitDateCombo = new javax.swing.JComboBox<>();
        WaitConfirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CustomerStatusCombo = new javax.swing.JComboBox<>();
        CustomerStatusConfirm = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CustomerStatusDisplay = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        CancelPassengerCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        CancelCustomerDateCombo = new javax.swing.JComboBox<>();
        CancelConfirm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        DropFlightCombo = new javax.swing.JComboBox<>();
        DropConfirm = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Scheduler");

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Scheduler");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Passenger Name:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        ConfirmCustomer.setText("Add Customer");
        ConfirmCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmCustomerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Date:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Flight");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Name:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Seat Amount:");

        FlightNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightNameTextActionPerformed(evt);
            }
        });

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });

        AddDay.setText("Add Day");
        AddDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDayActionPerformed(evt);
            }
        });

        DateChooser.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(AddFlight)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(36, 36, 36)
                                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ConfirmCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(SeatAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 247, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AddDay)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddFlight)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add", jPanel4);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Passenger:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Flight:");

        PassengerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        FlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FlightCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightComboActionPerformed(evt);
            }
        });

        ConfirmBooking.setText("Confirm");
        ConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBookingActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Date:");

        DateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(4);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(PassengerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(DateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmBooking))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PassengerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(DateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ConfirmBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Booking", jPanel5);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Flight:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Date:");

        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StatusConfirm.setText("Confirm");
        StatusConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatusFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatusDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(StatusConfirm)
                        .addGap(0, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(StatusFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(StatusDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusConfirm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Flight Status", jPanel6);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Date:");

        WaitDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        WaitConfirm.setText("Confirm");
        WaitConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WaitDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(WaitConfirm)
                        .addGap(0, 375, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(WaitDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WaitConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Wait List Status", jPanel7);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Passenger Name:");

        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CustomerStatusConfirm.setText("Confirm");
        CustomerStatusConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerStatusConfirmActionPerformed(evt);
            }
        });

        CustomerStatusDisplay.setColumns(20);
        CustomerStatusDisplay.setRows(5);
        CustomerStatusDisplay.setEnabled(false);
        jScrollPane4.setViewportView(CustomerStatusDisplay);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustomerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(CustomerStatusConfirm)))
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(CustomerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CustomerStatusConfirm))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Customer Status", jPanel1);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setText("Passenger:");

        CancelPassengerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Date:");

        CancelCustomerDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelConfirm.setText("Confirm");
        CancelConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelCustomerDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelPassengerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelConfirm))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CancelPassengerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CancelCustomerDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelConfirm)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Cancel Customer", jPanel2);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Flight:");

        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropConfirm.setText("Confirm");
        DropConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropConfirmActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DropConfirm)
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Drop Flight", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
        int result = passenger.addPassenger(nameText.getText());
        PassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        CancelPassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        JOptionPane.showMessageDialog(null, "Customer Succesfully Added to Database", "Notice", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_nameTextActionPerformed

    private void ConfirmCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmCustomerActionPerformed
        // TODO add your handling code here:
        int result = passenger.addPassenger(nameText.getText());
        PassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        CancelPassengerCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(passenger.selectAllPassenger().toArray()));
        JOptionPane.showMessageDialog(null, "Customer Succesfully Added to Database", "Notice", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_ConfirmCustomerActionPerformed

    private void StatusConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusConfirmActionPerformed
        // TODO add your handling code here:
        int numberOfEntries;
        jTextArea2.setText("");
        String flightName1 = StatusFlightCombo.getSelectedItem().toString();
        Date dateName1 = Date.valueOf(StatusDateCombo.getSelectedItem().toString());
        results = booking.getFlightStatus(flightName1, dateName1);
        numberOfEntries = results.size();

        
        for (int i=0; i<numberOfEntries; i++)
        {
            jTextArea2.append(results.get(i));   
            jTextArea2.append("\n");
        }
        
        
        
        //Object[] array = booking.getFlightStatus(flightName1, dateName1).toArray();
        //System.out.print(array);
        //jTextArea2.setText();
    }//GEN-LAST:event_StatusConfirmActionPerformed

    private void ConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBookingActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        String flightName = FlightCombo.getSelectedItem().toString();
        String passengerName = PassengerCombo.getSelectedItem().toString();
        Date dateName = Date.valueOf(DateCombo.getSelectedItem().toString());
        if (flight.getSeat(flightName) != booking.getFlightSeats(flightName, dateName))
            {
                booking.addBooking(passengerName, dateName, flightName);
                jTextArea1.setText("Successfully Booked");
            }
        else
            {
                waitlist.addWaitList(flightName, dateName, passengerName,currentTimestamp);
                jTextArea1.setText("Flight is currently completely booked. Added to WaitList");
            }
    }//GEN-LAST:event_ConfirmBookingActionPerformed

    private void FlightComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightComboActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_FlightComboActionPerformed

    private void WaitConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitConfirmActionPerformed
        // TODO add your handling code here:
        int numberOfEntries;
        List<String> namePassenger = null;
        List<String> nameFlight = null;
        jTextArea3.setText("Passenger \tFlight \n");
        Date dateName1 = Date.valueOf(WaitDateCombo.getSelectedItem().toString());
        results2 = waitlist.getWaitListStatus(dateName1);
        namePassenger = results2.get(0);
        nameFlight = results2.get(1);
        
        
        numberOfEntries = namePassenger.size();
        
        for (int i=0; i<numberOfEntries; i++)
        {
            jTextArea3.append((namePassenger.get(i) + "\t" +  nameFlight.get(i)));   
            jTextArea3.append("\n");
        }
    }//GEN-LAST:event_WaitConfirmActionPerformed

    private void FlightNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightNameTextActionPerformed

    private void CustomerStatusConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerStatusConfirmActionPerformed
        // TODO add your handling code here:
        int numberOfEntries;
        List<String> nameDate = null;
        List<String> nameFlight = null;
        CustomerStatusDisplay.setText("Flight \tDate \tList\n");
        String passengerName = CustomerStatusCombo.getSelectedItem().toString();
        results2 = booking.getCustomerStatus(passengerName);
        nameFlight = results2.get(0);
        nameDate = results2.get(1);
        
        
        numberOfEntries = nameFlight.size();
        
        for (int i=0; i<numberOfEntries; i++)
        {
            CustomerStatusDisplay.append((nameFlight.get(i) + "\t" +  nameDate.get(i)) + "\tBooking");   
            CustomerStatusDisplay.append("\n");
        }
        
        results2 = waitlist.getCustomerStatus(passengerName);
        nameFlight = results2.get(0);
        nameDate = results2.get(1);
        
        
        numberOfEntries = nameFlight.size();
        
        for (int i=0; i<numberOfEntries; i++)
        {
            CustomerStatusDisplay.append((nameFlight.get(i) + "\t" +  nameDate.get(i)) + "\tWaitlist");   
            CustomerStatusDisplay.append("\n");
        }
    }//GEN-LAST:event_CustomerStatusConfirmActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        // TODO add your handling code here:
        int result = flight.addFlight(FlightNameText.getText(),Integer.parseInt(SeatAmountText.getText()));
        FlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        
        JOptionPane.showMessageDialog(null, "Flight Succesfully Added to Database", "Notice", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void AddDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDayActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(DateChooser.getValue()); 
        Date day = Date.valueOf(spinnerValue);
        int result = date.addDate(day);
        DateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        WaitDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        CancelCustomerDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        
        JOptionPane.showMessageDialog(null, "Date Succesfully Added to Database", "Notice", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddDayActionPerformed

    private void DropConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropConfirmActionPerformed
        // TODO add your handling code here:
        jTextArea4.setText("");
        List<String> nameDate = null;
        List<String> namePassenger = null;
        List<String> waitName = null;
        List<String> waitDate =null;
        String flightName = DropFlightCombo.getSelectedItem().toString();
        results2 = booking.getFlightStatus(flightName);
        namePassenger = results2.get(0);
        nameDate = results2.get(1);
        flight.deleteFlight(flightName);
        booking.deleteFlight(flightName);
        result3 = waitlist.getCustomerName(flightName);
        waitName = result3.get(0);
        waitDate = result3.get(1);
        waitlist.deleteFlight(flightName);
        ///readd the people into different flights
        List <String> remainingFlights = flight.getFlight();
        
        int j = 0; // counter for the index position of the day/customer list
        for (int i=0; i<remainingFlights.size(); i++)
        {
            while ((flight.getSeat(remainingFlights.get(i))) != booking.getFlightSeats(remainingFlights.get(i), Date.valueOf(nameDate.get(j))))
            {
                booking.addBooking(namePassenger.get(j), Date.valueOf(nameDate.get(j)), remainingFlights.get(i));
                jTextArea4.append(namePassenger.get(j) + " has been booked to flight " + remainingFlights.get(i) + " on " + Date.valueOf(nameDate.get(j)) +"\n");
                j ++;
                
            }
        }
        while (j< nameDate.size())
        {
            jTextArea4.append(namePassenger.get(j) + " cannot be rebooked due to flight being full on " +Date.valueOf(nameDate.get(j))+".\n");
            j++;                
        }
        for (int i =0; i< waitName.size(); i++)
        {
            jTextArea4.append(waitName.get(i) + " cancelled from waitlist date " +waitDate.get(i)+".\n");
        }
        FlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
    }//GEN-LAST:event_DropConfirmActionPerformed

    private void CancelConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelConfirmActionPerformed
        // TODO add your handling code here:
        String name = CancelPassengerCombo.getSelectedItem().toString();
        String flight = null;
        String newName = null;
        String dateString = CancelCustomerDateCombo.getSelectedItem().toString();
        Date day = Date.valueOf(dateString);
        if (booking.inBooking(name, day) != null)
        {
            flight = booking.inBooking(name, day).get(0);
            booking.cancelCustomer(name, day);
            newName = waitlist.getFirstCustomer(flight, day);
            booking.addBooking(newName, day, flight);
            waitlist.cancelCustomer(newName, day);
            JOptionPane.showMessageDialog(null, "Cancel Booking Successful \n" +newName+" Is Now Booked On "+dateString, "Notice", JOptionPane.PLAIN_MESSAGE);
        
            
        }
        else if (waitlist.inWaitlist(name, day))
            {
                waitlist.cancelCustomer(name, day);
                JOptionPane.showMessageDialog(null, "Cancel WaitList Cuessful",  "Notice", JOptionPane.PLAIN_MESSAGE);
            }
        else
            JOptionPane.showMessageDialog(null, "Customer Not In Booking or Waitlist", "Notice", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_CancelConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDay;
    private javax.swing.JButton AddFlight;
    private javax.swing.JButton CancelConfirm;
    private javax.swing.JComboBox<String> CancelCustomerDateCombo;
    private javax.swing.JComboBox<String> CancelPassengerCombo;
    private javax.swing.JButton ConfirmBooking;
    private javax.swing.JButton ConfirmCustomer;
    private javax.swing.JComboBox<String> CustomerStatusCombo;
    private javax.swing.JButton CustomerStatusConfirm;
    private javax.swing.JTextArea CustomerStatusDisplay;
    private javax.swing.JSpinner DateChooser;
    private javax.swing.JComboBox<String> DateCombo;
    private javax.swing.JButton DropConfirm;
    private javax.swing.JComboBox<String> DropFlightCombo;
    private javax.swing.JComboBox<String> FlightCombo;
    private javax.swing.JTextField FlightNameText;
    private javax.swing.JComboBox<String> PassengerCombo;
    private javax.swing.JTextField SeatAmountText;
    private javax.swing.JButton StatusConfirm;
    private javax.swing.JComboBox<String> StatusDateCombo;
    private javax.swing.JComboBox<String> StatusFlightCombo;
    private javax.swing.JButton WaitConfirm;
    private javax.swing.JComboBox<String> WaitDateCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables
}
